### ISSUE TITLE
Inheritance 

### ISSUE THREAD

**Issue by juliemachamer** [BradfordMedeiros/arch#1]
Do you Student and Instructor should be written using  java inheritance? I don't really care, just wondering what y'all thought.

**Comment by BradfordMedeiros** [comment]
I appreciate the use of the issue tracker. 
I generally favor composition to inheritance.  If you want to change it feel free to send a pr.

**Comment by juliemachamer** [comment]
No prob! & thats fine with me, I only noticed but of the class diagram.
